#!/usr/bin/env bash
# deploy.sh — Kubernetes on Proxmox LXC
# Usage:
#   ./deploy.sh              # full deploy
#   ./deploy.sh --destroy    # tear down
#   ./deploy.sh --ansible    # ansible only (containers already up)
#   ./deploy.sh --from-step N  # resume from step N (1-4)

set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────────
# Resolve paths relative to this script so the repo can live anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/terraform"
ANSIBLE_DIR="$SCRIPT_DIR/ansible"
export ANSIBLE_DIR
SSH_KEY="$HOME/.ssh/k8s_proxmox"
KNOWN_HOSTS="$HOME/.ssh/known_hosts"
VENV="$HOME/ansible-venv/bin/activate"

# Proxmox host (pct runs there via SSH — the old laptop)
PROXMOX_HOST="${PROXMOX_HOST:-192.168.31.227}"
PROXMOX_SSH_USER="${PROXMOX_SSH_USER:-root}"
PROXMOX_SSH_KEY="${PROXMOX_SSH_KEY:-$HOME/.ssh/id_ed25519}"

# ── Helpers ───────────────────────────────────────────────────────────────────────────
banner() {
  echo ""
  echo "══════════════════════════════════════════"
  echo "  $1"
  echo "══════════════════════════════════════════"
}

get_ips() {
  cd "$TERRAFORM_DIR"
  terraform output -json | python3 -c "
import json, sys
data = json.load(sys.stdin)
for v in data.get('master_nodes',{}).get('value',{}).values(): print(v['ip'])
for v in data.get('worker_nodes',{}).get('value',{}).values(): print(v['ip'])
"
}

get_vm_ids() {
  cd "$TERRAFORM_DIR"
  terraform output -json | python3 -c "
import json, sys
data = json.load(sys.stdin)
for k,v in data.get('master_nodes',{}).get('value',{}).items(): print(v['vm_id'], k)
for k,v in data.get('worker_nodes',{}).get('value',{}).items(): print(v['vm_id'], k)
"
}

# Run pct on the Proxmox host over SSH (this script may live on a control node)
pct_remote() {
  ssh -i "$PROXMOX_SSH_KEY" -o BatchMode=yes -o StrictHostKeyChecking=no \
      -o ConnectTimeout=8 "$PROXMOX_SSH_USER@$PROXMOX_HOST" "pct $*"
}

# Re-apply the privileged lxc.conf patch on the Proxmox host over SSH
patch_lxc_conf_remote() {
  local vm_id=$1
  ssh -i "$PROXMOX_SSH_KEY" -o BatchMode=yes -o StrictHostKeyChecking=no \
      "$PROXMOX_SSH_USER@$PROXMOX_HOST" \
      "sed -i '/^lxc\./d' /etc/pve/lxc/${vm_id}.conf
       printf '%s\n' 'lxc.apparmor.profile: unconfined' 'lxc.cap.drop:' 'lxc.cgroup2.devices.allow: a' 'lxc.mount.auto: proc:rw sys:rw cgroup:rw' 'lxc.mount.entry: /dev/kmsg dev/kmsg none bind,create=file' >> /etc/pve/lxc/${vm_id}.conf"
}

clear_known_hosts() {
  banner "Clearing stale SSH known_hosts"
  for ip in $(get_ips); do
    ssh-keygen -f "$KNOWN_HOSTS" -R "$ip" 2>/dev/null || true
    echo "  Cleared: $ip"
  done
}

wait_for_ssh() {
  local ip=$1
  local timeout=180
  local elapsed=0
  printf "  Waiting for SSH on %s ." "$ip"
  while ! ssh -i "$SSH_KEY" \
      -o StrictHostKeyChecking=no \
      -o ConnectTimeout=3 \
      -o BatchMode=yes \
      root@"$ip" true 2>/dev/null; do
    sleep 5
    elapsed=$((elapsed + 5))
    printf "."
    if [ $elapsed -ge $timeout ]; then
      echo " TIMEOUT"
      echo "ERROR: $ip never became reachable. Check: pct status <id>"
      exit 1
    fi
  done
  echo " UP"
}

# ── Steps ─────────────────────────────────────────────────────────────────────
step_terraform() {
  banner "Step 1 — Terraform: provision + patch LXC containers"
  cd "$TERRAFORM_DIR"
  terraform init -upgrade
  terraform apply -auto-approve
  echo ""
  echo "  Containers created and lxc.conf patched via null_resource ✓"
}

step_wait() {
  banner "Step 2 — Wait for containers to be SSH-ready"

  # Verify all containers are running (null_resource starts them,
  # but this is a safety net in case any are still stopped)
  echo "  Checking container states..."
  while read -r vm_id name; do
    status=$(pct_remote status "$vm_id" 2>&1)
    echo "  $name (CT $vm_id): $status"
    if echo "$status" | grep -qi "stopped"; then
      echo "  ⚠  CT $vm_id stopped — patching lxc.conf and starting..."
      pct_remote stop "$vm_id" 2>/dev/null || true
      sleep 2
      patch_lxc_conf_remote "$vm_id"
      pct_remote start "$vm_id"
      echo "  CT $vm_id started ✓"
    fi
  done < <(get_vm_ids)

  echo ""
  echo "  Waiting 25s for SSH services to initialize inside containers..."
  sleep 25

  clear_known_hosts

  echo ""
  for ip in $(get_ips); do
    wait_for_ssh "$ip"
  done
  echo ""
  echo "  All containers reachable ✓"
}

step_inventory() {
  banner "Step 3 — Generate Ansible inventory"

  # Write inventory generator to a temp file (can't pipe + heredoc together)
  cat > /tmp/gen_inventory.py << 'PYEOF'
import json, sys, os

data = json.load(sys.stdin)
masters    = data["master_nodes"]["value"]
workers    = data["worker_nodes"]["value"]
primary_ip = data["primary_master_ip"]["value"]

ini  = "# Auto-generated by deploy.sh — do not edit\n\n"
ini += "[masters]\n"
for v in sorted(masters.values(), key=lambda x: x["hostname"]):
    ini += f"{v['hostname']}  ansible_host={v['ip']}  ansible_user=root\n"
ini += "\n[workers]\n"
for v in sorted(workers.values(), key=lambda x: x["hostname"]):
    ini += f"{v['hostname']}  ansible_host={v['ip']}  ansible_user=root\n"
ini += "\n[k8s_cluster:children]\nmasters\nworkers\n"
ini += (
    f"\n[k8s_cluster:vars]\n"
    f"ansible_ssh_common_args='-o StrictHostKeyChecking=no'\n"
    f"primary_master_ip={primary_ip}\n"
)

ansible_dir = os.environ.get("ANSIBLE_DIR") or os.path.expanduser("~/k8s-proxmox/ansible")
path = os.path.join(ansible_dir, "inventory", "hosts.ini")
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    f.write(ini)

print(ini)
print(f"  Written to {path}")
PYEOF

  cd "$TERRAFORM_DIR"
  terraform output -json | python3 /tmp/gen_inventory.py
}

step_ansible() {
  banner "Step 4 — Ansible: configure Kubernetes cluster"
  if [ -f "$VENV" ]; then
    # shellcheck disable=SC1090
    source "$VENV"
  else
    echo "  (venv $VENV not found — using system ansible)"
  fi
  cd "$ANSIBLE_DIR"
  ansible-playbook site.yml
}

step_destroy() {
  banner "Destroying cluster"
  mapfile -t IPS < <(get_ips 2>/dev/null || true)

  cd "$TERRAFORM_DIR"
  terraform destroy -auto-approve

  for ip in "${IPS[@]}"; do
    ssh-keygen -f "$KNOWN_HOSTS" -R "$ip" 2>/dev/null || true
    echo "  Cleared SSH key: $ip"
  done
  echo ""
  echo "  Cluster destroyed and SSH keys cleaned ✓"
}

# ── Entry point ───────────────────────────────────────────────────────────────
main() {
  case "${1:-}" in
    --destroy)
      step_destroy
      ;;
    --ansible)
      clear_known_hosts
      step_inventory
      step_ansible
      ;;
    --from-step)
      START="${2:-1}"
      [ "$START" -le 1 ] && step_terraform
      [ "$START" -le 2 ] && step_wait
      [ "$START" -le 3 ] && step_inventory
      [ "$START" -le 4 ] && step_ansible
      ;;
    "")
      step_terraform
      step_wait
      step_inventory
      step_ansible
      banner "Deployment complete!"
      MASTER_IP=$(cd "$TERRAFORM_DIR" && terraform output -raw primary_master_ip)
      echo ""
      echo "  Check nodes : ssh -i $SSH_KEY root@$MASTER_IP 'kubectl get nodes'"
      echo "  Jellyfin    : http://jellyfin.home.lab  (point DNS at the gateway's MetalLB IP)"
      echo ""
      ;;
    *)
      echo "Usage: $0 [--destroy | --ansible | --from-step N]"
      exit 1
      ;;
  esac
}

main "$@"
